# Generated by Django 4.1.1 on 2022-10-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.passenger')),
            ],
        ),
    ]
