# Generated by Django 4.1.1 on 2022-10-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=5)),
                ('capacity', models.IntegerField()),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.passenger')),
            ],
        ),
    ]
