# Generated by Django 4.1.1 on 2022-10-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dprt_loc', models.CharField(max_length=20)),
                ('dest', models.CharField(max_length=20)),
                ('arrv_time', models.CharField(max_length=5)),
                ('sc_date', models.DateField()),
                ('dprt_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
    ]
