# Generated by Django 4.1.1 on 2022-10-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
        ('bus', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tot_num_seats', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('tot_amount', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.passenger')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.schedule')),
            ],
        ),
    ]
