# Generated by Django 4.1.1 on 2022-10-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
        ('bus', '0003_ticket_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.passenger')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.schedule')),
                ('ticket_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.ticket_booking')),
            ],
        ),
    ]
