# Generated by Django 4.1.1 on 2022-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_remove_seats_seat_number_ticket_booking_from_dist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_booking',
            name='to_dist',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
