# Generated by Django 4.1.1 on 2022-12-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_ticket_booking_to_dist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='ticket_booking',
            new_name='ticketbooking',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='arrv_time',
        ),
    ]
