# Generated by Django 4.1.1 on 2022-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_rename_ticket_booking_seats_ticketbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dprt_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sc_date',
            field=models.DateField(null=True),
        ),
    ]
