# Generated by Django 4.1.1 on 2022-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_schedule_dprt_time_alter_schedule_sc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
